services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - singe
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - singe
  www:
    image: warden696/php:fpm-alpine3.20-latest
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/symfony:cached
    networks:
      - singe
    entrypoint: [ "/bin/sh", "-c", "chmod +x /var/www/symfony/init.sh && /var/www/symfony/init.sh && php-fpm" ]

volumes:
  db-data:


networks:
  singe:
    driver: bridge
